### ISSUE TITLE
real m(-2:1, 0:4) 定义

### ISSUE THREAD

**Issue by tianzhuqiao** [zhonger/fortran-tutorial#3]
在basic.md中有一个笔误

`real m(-2:1, 0:4) 表示定义一个 3 行 x 4 列、行序号从 -2 到 0、列序号从 1 到 4 的二维数组`
应该是一个 4行 x 5 列、行序号从 -2 到 1、列序号从 0 到 4 的二维数组？

**Comment by tianzhuqiao** [comment]
condition.md 中示例 16也有笔误
```
!!! 示例 16
sum = 0
do i = 1, 10
    sum = sum + i
    if (sum <= 10) cycle
enddo
print *, i, sum      ! 输出 i 的值仍为 5，sum 的值仍为 15
```

**Comment by zhonger** [comment]
感谢指出这两处错误。
第一处的确应该是你指出的那样，需要算上序号 0。
第二处 cycle 的用法需要后面有其他语句才能生效，现在的代码执行完全不影响求和。

相应的修改在：   3566b72   801b0c5
